[2025-02-18T11:29:22.650+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T11:29:22.663+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: snowflake_reading.snowflake_reader manual__2025-02-18T11:29:22.263075+00:00 [queued]>
[2025-02-18T11:29:22.671+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: snowflake_reading.snowflake_reader manual__2025-02-18T11:29:22.263075+00:00 [queued]>
[2025-02-18T11:29:22.671+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-18T11:29:22.693+0000] {taskinstance.py:2889} INFO - Executing <Task(SparkSubmitOperator): snowflake_reader> on 2025-02-18 11:29:22.263075+00:00
[2025-02-18T11:29:22.699+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'snowflake_reading', 'snowflake_reader', 'manual__2025-02-18T11:29:22.263075+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/snowflake_reading.py', '--cfg-path', '/tmp/tmpq3j18qyj']
[2025-02-18T11:29:22.702+0000] {standard_task_runner.py:105} INFO - Job 100: Subtask snowflake_reader
[2025-02-18T11:29:22.705+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1247) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-18T11:29:22.706+0000] {standard_task_runner.py:72} INFO - Started process 1249 to run task
[2025-02-18T11:29:22.741+0000] {task_command.py:467} INFO - Running <TaskInstance: snowflake_reading.snowflake_reader manual__2025-02-18T11:29:22.263075+00:00 [running]> on host 944871224fc0
[2025-02-18T11:29:22.808+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='snowflake_reading' AIRFLOW_CTX_TASK_ID='snowflake_reader' AIRFLOW_CTX_EXECUTION_DATE='2025-02-18T11:29:22.263075+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-18T11:29:22.263075+00:00'
[2025-02-18T11:29:22.808+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-18T11:29:22.830+0000] {base.py:84} INFO - Retrieving connection 'spark_default'
[2025-02-18T11:29:22.831+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077:7077 --conf spark.driver.extraClassPath=/usr/local/app/jars/snowflake-jdbc-3.13.14.jar --jars /usr/local/app/jars/snowflake-jdbc-3.13.14.jar --name arrow-spark --deploy-mode client /usr/local/app/spark_applications/read_snowflake_data.py
[2025-02-18T11:29:22.872+0000] {spark_submit.py:641} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-02-18T11:29:24.470+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:24 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-02-18T11:29:25.602+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:25 INFO SparkContext: Running Spark version 3.5.4
[2025-02-18T11:29:25.603+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:25 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-02-18T11:29:25.603+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:25 INFO SparkContext: Java version 17.0.14
[2025-02-18T11:29:25.621+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:25 INFO ResourceUtils: ==============================================================
[2025-02-18T11:29:25.621+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:25 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-02-18T11:29:25.622+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:25 INFO ResourceUtils: ==============================================================
[2025-02-18T11:29:25.622+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:25 INFO SparkContext: Submitted application: SnowflakeRead
[2025-02-18T11:29:25.635+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:25 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-02-18T11:29:25.641+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:25 INFO ResourceProfile: Limiting resource is cpu
[2025-02-18T11:29:25.642+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:25 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-02-18T11:29:25.677+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:25 INFO SecurityManager: Changing view acls to: default
[2025-02-18T11:29:25.678+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:25 INFO SecurityManager: Changing modify acls to: default
[2025-02-18T11:29:25.678+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:25 INFO SecurityManager: Changing view acls groups to:
[2025-02-18T11:29:25.679+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:25 INFO SecurityManager: Changing modify acls groups to:
[2025-02-18T11:29:25.679+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:25 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2025-02-18T11:29:25.848+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:25 INFO Utils: Successfully started service 'sparkDriver' on port 38947.
[2025-02-18T11:29:25.869+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:25 INFO SparkEnv: Registering MapOutputTracker
[2025-02-18T11:29:25.894+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:25 INFO SparkEnv: Registering BlockManagerMaster
[2025-02-18T11:29:25.908+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:25 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-02-18T11:29:25.909+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:25 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-02-18T11:29:25.912+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:25 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-02-18T11:29:25.930+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:25 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-56080880-4b13-4881-910a-439474fe078b
[2025-02-18T11:29:25.941+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:25 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-02-18T11:29:25.954+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:25 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-02-18T11:29:26.070+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:26 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-02-18T11:29:26.131+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:26 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-02-18T11:29:26.167+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:26 INFO SparkContext: Added JAR file:///usr/local/app/jars/snowflake-jdbc-3.13.14.jar at spark://944871224fc0:38947/jars/snowflake-jdbc-3.13.14.jar with timestamp 1739878165596
[2025-02-18T11:29:26.229+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:26 ERROR SparkContext: Error initializing SparkContext.
[2025-02-18T11:29:26.230+0000] {spark_submit.py:641} INFO - org.apache.spark.SparkException: Invalid master URL: spark://spark:7077:7077
[2025-02-18T11:29:26.230+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.Utils$.extractHostPortFromSparkUrl(Utils.scala:2401)
[2025-02-18T11:29:26.231+0000] {spark_submit.py:641} INFO - at org.apache.spark.rpc.RpcAddress$.fromSparkURL(RpcAddress.scala:54)
[2025-02-18T11:29:26.231+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.client.StandaloneAppClient.$anonfun$masterRpcAddresses$1(StandaloneAppClient.scala:54)
[2025-02-18T11:29:26.232+0000] {spark_submit.py:641} INFO - at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
[2025-02-18T11:29:26.232+0000] {spark_submit.py:641} INFO - at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
[2025-02-18T11:29:26.233+0000] {spark_submit.py:641} INFO - at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
[2025-02-18T11:29:26.233+0000] {spark_submit.py:641} INFO - at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
[2025-02-18T11:29:26.234+0000] {spark_submit.py:641} INFO - at scala.collection.TraversableLike.map(TraversableLike.scala:286)
[2025-02-18T11:29:26.234+0000] {spark_submit.py:641} INFO - at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
[2025-02-18T11:29:26.235+0000] {spark_submit.py:641} INFO - at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
[2025-02-18T11:29:26.235+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.client.StandaloneAppClient.<init>(StandaloneAppClient.scala:54)
[2025-02-18T11:29:26.236+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.cluster.StandaloneSchedulerBackend.start(StandaloneSchedulerBackend.scala:134)
[2025-02-18T11:29:26.236+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:235)
[2025-02-18T11:29:26.237+0000] {spark_submit.py:641} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:599)
[2025-02-18T11:29:26.237+0000] {spark_submit.py:641} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2025-02-18T11:29:26.238+0000] {spark_submit.py:641} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-02-18T11:29:26.238+0000] {spark_submit.py:641} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-02-18T11:29:26.238+0000] {spark_submit.py:641} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-02-18T11:29:26.239+0000] {spark_submit.py:641} INFO - at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-02-18T11:29:26.239+0000] {spark_submit.py:641} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-02-18T11:29:26.239+0000] {spark_submit.py:641} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2025-02-18T11:29:26.240+0000] {spark_submit.py:641} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-02-18T11:29:26.240+0000] {spark_submit.py:641} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2025-02-18T11:29:26.240+0000] {spark_submit.py:641} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2025-02-18T11:29:26.241+0000] {spark_submit.py:641} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2025-02-18T11:29:26.241+0000] {spark_submit.py:641} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-02-18T11:29:26.241+0000] {spark_submit.py:641} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-02-18T11:29:26.241+0000] {spark_submit.py:641} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2025-02-18T11:29:26.241+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:26 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-02-18T11:29:26.242+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:26 INFO SparkUI: Stopped Spark web UI at http://944871224fc0:4040
[2025-02-18T11:29:26.245+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:26 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-02-18T11:29:26.248+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:26 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2025-02-18T11:29:26.263+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:26 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-02-18T11:29:26.270+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:26 INFO MemoryStore: MemoryStore cleared
[2025-02-18T11:29:26.270+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:26 INFO BlockManager: BlockManager stopped
[2025-02-18T11:29:26.275+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:26 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-02-18T11:29:26.276+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:26 WARN MetricsSystem: Stopping a MetricsSystem that is not running
[2025-02-18T11:29:26.277+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:26 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-02-18T11:29:26.285+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:26 INFO SparkContext: Successfully stopped SparkContext
[2025-02-18T11:29:26.285+0000] {spark_submit.py:641} INFO - Traceback (most recent call last):
[2025-02-18T11:29:26.286+0000] {spark_submit.py:641} INFO - File "/usr/local/app/spark_applications/read_snowflake_data.py", line 18, in <module>
[2025-02-18T11:29:26.287+0000] {spark_submit.py:641} INFO - main()
[2025-02-18T11:29:26.288+0000] {spark_submit.py:641} INFO - File "/usr/local/app/spark_applications/read_snowflake_data.py", line 8, in main
[2025-02-18T11:29:26.289+0000] {spark_submit.py:641} INFO - .getOrCreate()
[2025-02-18T11:29:26.290+0000] {spark_submit.py:641} INFO - ^^^^^^^^^^^^^
[2025-02-18T11:29:26.290+0000] {spark_submit.py:641} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 497, in getOrCreate
[2025-02-18T11:29:26.291+0000] {spark_submit.py:641} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 515, in getOrCreate
[2025-02-18T11:29:26.291+0000] {spark_submit.py:641} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 203, in __init__
[2025-02-18T11:29:26.292+0000] {spark_submit.py:641} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 296, in _do_init
[2025-02-18T11:29:26.292+0000] {spark_submit.py:641} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 421, in _initialize_context
[2025-02-18T11:29:26.293+0000] {spark_submit.py:641} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1587, in __call__
[2025-02-18T11:29:26.294+0000] {spark_submit.py:641} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-02-18T11:29:26.295+0000] {spark_submit.py:641} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
[2025-02-18T11:29:26.296+0000] {spark_submit.py:641} INFO - : org.apache.spark.SparkException: Invalid master URL: spark://spark:7077:7077
[2025-02-18T11:29:26.296+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.Utils$.extractHostPortFromSparkUrl(Utils.scala:2401)
[2025-02-18T11:29:26.296+0000] {spark_submit.py:641} INFO - at org.apache.spark.rpc.RpcAddress$.fromSparkURL(RpcAddress.scala:54)
[2025-02-18T11:29:26.297+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.client.StandaloneAppClient.$anonfun$masterRpcAddresses$1(StandaloneAppClient.scala:54)
[2025-02-18T11:29:26.297+0000] {spark_submit.py:641} INFO - at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
[2025-02-18T11:29:26.298+0000] {spark_submit.py:641} INFO - at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
[2025-02-18T11:29:26.298+0000] {spark_submit.py:641} INFO - at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
[2025-02-18T11:29:26.299+0000] {spark_submit.py:641} INFO - at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
[2025-02-18T11:29:26.299+0000] {spark_submit.py:641} INFO - at scala.collection.TraversableLike.map(TraversableLike.scala:286)
[2025-02-18T11:29:26.299+0000] {spark_submit.py:641} INFO - at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
[2025-02-18T11:29:26.300+0000] {spark_submit.py:641} INFO - at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
[2025-02-18T11:29:26.300+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.client.StandaloneAppClient.<init>(StandaloneAppClient.scala:54)
[2025-02-18T11:29:26.300+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.cluster.StandaloneSchedulerBackend.start(StandaloneSchedulerBackend.scala:134)
[2025-02-18T11:29:26.300+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:235)
[2025-02-18T11:29:26.301+0000] {spark_submit.py:641} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:599)
[2025-02-18T11:29:26.301+0000] {spark_submit.py:641} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2025-02-18T11:29:26.301+0000] {spark_submit.py:641} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-02-18T11:29:26.302+0000] {spark_submit.py:641} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-02-18T11:29:26.302+0000] {spark_submit.py:641} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-02-18T11:29:26.302+0000] {spark_submit.py:641} INFO - at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-02-18T11:29:26.302+0000] {spark_submit.py:641} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-02-18T11:29:26.303+0000] {spark_submit.py:641} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2025-02-18T11:29:26.303+0000] {spark_submit.py:641} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-02-18T11:29:26.303+0000] {spark_submit.py:641} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2025-02-18T11:29:26.303+0000] {spark_submit.py:641} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2025-02-18T11:29:26.303+0000] {spark_submit.py:641} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2025-02-18T11:29:26.304+0000] {spark_submit.py:641} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-02-18T11:29:26.304+0000] {spark_submit.py:641} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-02-18T11:29:26.304+0000] {spark_submit.py:641} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2025-02-18T11:29:26.304+0000] {spark_submit.py:641} INFO - 
[2025-02-18T11:29:26.339+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:26 INFO ShutdownHookManager: Shutdown hook called
[2025-02-18T11:29:26.339+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:26 INFO ShutdownHookManager: Deleting directory /tmp/spark-5d2cc685-3054-4315-adff-0aad57b5f3b6
[2025-02-18T11:29:26.343+0000] {spark_submit.py:641} INFO - 25/02/18 11:29:26 INFO ShutdownHookManager: Deleting directory /tmp/spark-ab3dce3c-830f-45e2-9d35-a7b9d2f7682e
[2025-02-18T11:29:26.372+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077:7077 --conf spark.driver.extraClassPath=/usr/local/app/jars/snowflake-jdbc-3.13.14.jar --jars /usr/local/app/jars/snowflake-jdbc-3.13.14.jar --name arrow-spark --deploy-mode client /usr/local/app/spark_applications/read_snowflake_data.py. Error code is: 1.
[2025-02-18T11:29:26.376+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=snowflake_reading, task_id=snowflake_reader, run_id=manual__2025-02-18T11:29:22.263075+00:00, execution_date=20250218T112922, start_date=20250218T112922, end_date=20250218T112926
[2025-02-18T11:29:26.389+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-18T11:29:26.390+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 100 for task snowflake_reader (Cannot execute: spark-submit --master spark://spark:7077:7077 --conf spark.driver.extraClassPath=/usr/local/app/jars/snowflake-jdbc-3.13.14.jar --jars /usr/local/app/jars/snowflake-jdbc-3.13.14.jar --name arrow-spark --deploy-mode client /usr/local/app/spark_applications/read_snowflake_data.py. Error code is: 1.; 1249)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077:7077 --conf spark.driver.extraClassPath=/usr/local/app/jars/snowflake-jdbc-3.13.14.jar --jars /usr/local/app/jars/snowflake-jdbc-3.13.14.jar --name arrow-spark --deploy-mode client /usr/local/app/spark_applications/read_snowflake_data.py. Error code is: 1.
[2025-02-18T11:29:26.411+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-18T11:29:26.422+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-18T11:29:26.424+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
